name: testing

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install "streamlit==1.36.0" toml pytest pytest-playwright pytest-rerunfailures
          playwright install chromium --with-deps
      - name: Test
        env:
          PYTHONPATH: src
        run: pytest --browser chromium --reruns 3
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots-${{ matrix.python-version }}
          path: screenshot*.png
